name: Deploy app to Firebase

'on':
  push:
    branches:
      - v17

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v17
      - uses: actions/setup-node@v17
        with:
          node-version: '12.x'
      - run: npm install
      - run: npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_CREANDO_CARINO }}'
          channelId: live
          projectId: creando-carino
